#!/usr/bin/env bash
#comment

filename=school
if [ -f "$filename" ];then
	echo "school file exists"
else
	echo "school file does not exists"
fi
if [ -s "$filename" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
